# Generated by Django 5.0.4 on 2024-05-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_zarinpal_other_verify_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zarinpal_other_verify_data',
            new_name='zarinpal_verify_data',
        ),
    ]
